--- Makefile	2024-08-11 14:08:06.114532100 +0200
+++ Makefile_mod	2024-08-11 14:10:43.244536191 +0200
@@ -1856,6 +1856,7 @@
 	@$(SEP)
 	@$(MAKE) -C $@ all $(PARALLEL_BUILD)
 	@$(MAKE) -C $@ DESTDIR=$(TOP)/sqlite/staged install
+	sed "s|'/usr/lib|'$(TOP)/sqlite/staged/usr/lib|g" -i $(TOP)/sqlite/staged/usr/lib/libsqlite3.la
 
 sqlite-install:
 ifeq ($(or $(TCONFIG_NGINX),$(TCONFIG_MEDIA_SERVER)),y)
@@ -2475,6 +2476,7 @@
 	@$(MAKE) -C $@ DESTDIR=$(TOP)/libpng/staged install
 	@rm -f $(TOP)/libpng/staged/usr/lib/libpng.la
 	@rm -f $(TOP)/libpng/staged/usr/lib/libpng12.la
+	sed "s|'/usr/lib|'$(TOP)/libpng/staged/usr/lib|g" -i $(TOP)/libpng/staged/usr/lib/libpng16.la
 
 libpng-install:
 	install -D libpng/.libs/libpng16.so.16.43.0 $(INSTALLDIR)/libpng/usr/lib/libpng16.so.16.43.0
@@ -3786,6 +3788,7 @@
 	@$(SEP)
 	@$(MAKE) -C $@ $(PARALLEL_BUILD)
 	@$(MAKE) -C $@ DESTDIR=$(TOP)/expat/staged install
+	sed "s|'/usr/lib|'$(TOP)/expat/staged/usr/lib|g" -i $(TOP)/expat/staged/usr/lib/libexpat.la
 
 expat-install:
 	install -D expat/staged/usr/lib/libexpat.so.1.9.2 $(INSTALLDIR)/expat/usr/lib/libexpat.so.1.9.2
