#! /bin/sh

FT_PATCHES_DIR=$HOME/documents/freshtomato-arm
FT_REPO_DIR=$HOME/freshtomato-arm

PATH="$PATH:$FT_REPO_DIR/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin"
#export PERL5LIB=/usr/share/autoconf:/usr/share/automake-1.16

cd $FT_REPO_DIR 
git clean -dxf 
git reset --hard
#git pull

git checkout arm-sdk7


patch -i $FT_PATCHES_DIR/common.mak.patch $FT_REPO_DIR/release/src-rt-6.x.4708/router/common.mak
patch -i $FT_PATCHES_DIR/Makefile_arm7.patch $FT_REPO_DIR/release/src-rt-6.x.4708/router/Makefile
patch -i $FT_PATCHES_DIR/configure.ac_tor.patch $FT_REPO_DIR/release/src-rt-6.x.4708/router/tor/configure.ac
patch -i $FT_PATCHES_DIR/genconfig.sh.patch $FT_REPO_DIR/release/src-rt-6.x.4708/router/miniupnpd/genconfig.sh

cd release/src-rt-7.x.main/src

time make ac3200z
# AIO:z; VPN:e > build.txt
